spring:
  application:
    name: activemqqq
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:jdbc: mysql://localhost:3306
    username: root
    password: 123456

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
